### ISSUE TITLE
Task 1: Hello World

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/bootcamp_FD30#1]
Topic Covered:
Installation Nodejs

Install Node js in your system and run the command

`console.log("Hello ! world");`

Share me the screenshots of the output that you will get just like the example below on the comments

![Image](https://user-images.githubusercontent.com/128008784/238532387-38b79483-f666-4a04-81f9-353cd0e9bc17.png)

**Comment by yogeshtakeo** [comment]
Yogesh Bhattarai

![image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/128008784/761639ac-94a3-4a4d-9cb3-95e9eee1d883)

**Comment by uniquemozilla22** [comment]
Yogesh Bhattarai
![image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/49606627/355cfa69-2827-4298-a140-30b69aa5844f)

**Comment by ashmaupret100** [comment]
Ashma Upreti

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/abf27dc3-90e4-4fe0-8d7d-ceee2c378411)

Graded : 10

**Comment by sandessth** [comment]
Sandesh Shrestha,
![Capture](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729653/a5d6bb08-954d-47d7-a753-6e3dfcf923b7)

Graded: 10

**Comment by dinakc** [comment]
now

**Comment by Namsla** [comment]
Namkhang Tsamchoe
<img width="457" alt="Screen Shot 2023-05-16 at 12 31 32 AM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/a89afb33-b6e5-499c-a36c-2994e52780a9">

Graded :10

**Comment by junuthapa011** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133033600/8edad169-e778-4ffa-a8fa-746a5b9c2b39)

Graded: 10

**Comment by dinakc** [comment]
![image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/105759959/c74d8268-a63b-4324-b4ea-3ed04a28e585)


Graded : 10

**Comment by Jharanatmg** [comment]
Jharana tag
<img width="543" alt="Screenshot 2023-05-15 at 10 20 04 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729796/e3f9e75f-9755-4503-aa87-35ff7f7bd140">


Graded : 10

**Comment by KabinaThapa** [comment]
![Screenshot (750)](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/de561e3c-1933-4f1d-ba35-4412dc6b72ef)

**Comment by babisha** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/23157110/cd94032a-30f8-4349-b128-0ef858f27239)

**Comment by sdhital12** [comment]
<img width="1440" alt="Screen Shot 2023-05-22 at 4 40 15 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/110055420/fd9bc26f-fd11-4c42-a538-110a1100f822">
