### ISSUE TITLE
Task 2 :  Github

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/bootcamp_FD30#2]
# Task 2: Creating a Repository and Pushing Files
## Objective:
Create a new repository on GitHub and push files to it using Git.

## Task Overview

- Learn how to create a repository on GitHub.
- Initialize a local Git repository and connect it to the remote repository.
- Push files from your local machine to the remote repository.

## Task Details

1. Watch a tutorial video or read an article on creating repositories on GitHub.
2. Sign in to your GitHub account.
3. Click on the "+" icon in the top-right corner and select "New repository" from the dropdown menu.
4. Provide a name for your repository (e.g., "frontend-bootcamp-tasks") and an optional description.
5. Choose the visibility (public or private) for your repository.
6. Optionally, select the option to initialize the repository with a README file.
7. Click on the "Create repository" button to create the repository on GitHub.

Now, let's move to the local machine:

Open a terminal or command prompt and navigate to your project directory.
Initialize a new Git repository in your project directory using the command:

`git init`

Add the files you want to push to the repository. For example, if you have an HTML file called "index.html" and a CSS file called "styles.css" in your project directory, use the following command to add them:

`git add .`

Commit the changes with a descriptive message using the command:

`git commit -m "Initial commit"`
Connect your local repository to the remote repository on GitHub using the following command:

`git remote add origin https://github.com/your-username/frontend-bootcamp-tasks.git`

Push the changes to the remote repository using the command:
`git push origin master`

**Verify that the files have been pushed to your GitHub repository by visiting the repository's page on GitHub.**

## Task Submission

Take a screenshot of your GitHub repository showing the pushed files.
Share the screenshot on the issues comment of this issue.

**Comment by Namsla** [comment]
<img width="1017" alt="Screen Shot 2023-05-16 at 11 27 00 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/39bff0e0-d560-4346-804e-da3ce86dad7f">
<img width="1303" alt="Screen Shot 2023-05-16 at 11 27 46 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/01d60db4-7fc5-40e8-917f-8a0b500990ed">

**Comment by sdhital12** [comment]
![image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/110055420/b2159bb0-4f36-47dd-8910-20aed0b7663d)

**Comment by sandessth** [comment]
sandesh shrestha

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729653/a087cf54-04b2-4057-9001-5d9a94991d9f)

**Comment by junuthapa011** [comment]
Name: Junu Thapa
Repository URL:  https://github.com/junuthapa011/BootcampFDB30.git

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133033600/8f219ff2-862a-410f-8a57-2308ee87e654)

**Comment by KabinaThapa** [comment]
/

**Comment by Namsla** [comment]
https://github.com/Namsla/Repository
<img width="1017" alt="Screen Shot 2023-05-16 at 11 27 00 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/5d09d731-28ca-4b9a-8ba7-172ddb315d85">

**Comment by Namsla** [comment]
Name: Namkhang Tsamchoe
Github link: https://github.com/Namsla/Repository.git

[
](https://github.com/Namsla/Repository)<img width="958" alt="Screen Shot 2023-05-17 at 12 19 49 AM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/625c21f0-eaea-4367-aeaf-09b4807f1929">

**Comment by KabinaThapa** [comment]
Kabina Thapa

https://github.com/KabinaThapa/Bootcamp-frontend-task2

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/d0416d0e-2a6b-40c9-91fe-abdd4bd1a38f)
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/e7ed155d-520d-407a-958c-247c428464e5)

**Comment by ashmaupret100** [comment]
Ashma

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/99503a0e-0cfe-49f5-a2ea-4440adfbee61)



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/b2d9ab21-f9d2-4be4-a09d-cff17d6bc47b)

**Comment by sandessth** [comment]
Sandesh Shrestha
https://github.com/sandessth/day_2

![day2_add repository](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729653/86505b18-4f89-4ed6-b421-262339331801)

**Comment by ashmaupret100** [comment]
ashma


![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/40e5aa29-f420-4065-be98-e56dbd817e1a)

**Comment by dinakc** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/105759959/3ebaa529-88d3-4b30-94e2-6c4fd81d3277)

**Comment by Jharanatmg** [comment]
Jharana 
<img width="911" alt="Task 2" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729796/d7e0cf5b-4fc0-4389-bbf9-7c452b81baf1">

**Comment by Jharanatmg** [comment]
Jharana 
https://github.com/Jharanatmg/Task-2-CP.git
<img width="911" alt="Task 2" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729796/4c32ee7d-86c4-4e39-ac92-ce22686fad9e">

**Comment by dinakc** [comment]
Deena KC
https://github.com/dinakc/indexhtml.git


![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/105759959/cc7f0f4f-8d8f-417d-b0d5-a0798564e3bf)

**Comment by ashmaupret100** [comment]
Name: Ashma Upreti
Github link : git@github.com:ashmaupret100/git_task2.git

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/36310182-84eb-4692-9128-341c62405ea0)

**Comment by babisha** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/23157110/e17fdcc3-6ceb-4d43-aef1-ad88402b6fb7)
