### ISSUE TITLE
Task 3 : Vite React Project

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/bootcamp_FD30#3]
# **Task 3: Creating a React Project with Create Vite App and Publishing on GitHub**

## Objective: 
Create a new React project using Create Vite App, make changes to the application, and publish it on GitHub.

## Task Overview

- Set up a React project using Create Vite App.
- Make changes to the React application.
- Publish the project on GitHub.

## Task Details
Install Node.js: Ensure that Node.js is installed on your computer by visiting https://nodejs.org/ and downloading the latest LTS version.

### Set up the Project:

Open a terminal or command prompt.
Create a new directory for your project:

`mkdir react-vite-project`

Go inside the project.

`cd react-vite-project`

Set up a new React project using Create Vite App by running the following command:

`npx create-vite@latest my-react-app --template react`

Wait for the project scaffolding to be completed.

### Explore the Project:

Open the project directory in your code editor.

Take a look at the project structure and files, including the src directory, App.jsx, and main.jsx.

### Make Changes to the Application:

Open src/App.jsx in your code editor.

Modify the content of the App component by adding or changing some text or elements.

Save the file to see the changes in the browser.

### Test the Application:

Open a terminal or command prompt in the project directory.

Start the development server by running the following command:
` npm run dev `

Open your web browser and navigate to the provided local development server URL (e.g., http://localhost:3000).

Verify that your changes are reflected in the browser.

### Create a GitHub Repository:

Sign in to your GitHub account.

Click on the "+" icon in the top-right corner and select "New repository" from the dropdown menu.

Provide a name for your repository (e.g., "my-react-app") and an optional description.

Choose the visibility (public or private) for your repository.

Click on the "Create repository" button to create the repository on GitHub.

### Publish the Project to GitHub:

Back in the terminal or command prompt, navigate to your project directory.

Initialize a new Git repository in your project directory if you haven't already done so:

`git init`

Add all the project files to the repository:

`git add .`

Commit the changes with a descriptive message:

`git commit -m "Initial commit: Create React app with Create Vite App"`

Connect your local repository to the remote repository on GitHub using the following command:

`git remote add origin https://github.com/your-username/my-react-app.git`

Push the changes to the remote repository:

`git push -u origin main`

### Verify the Published Project:

Visit your GitHub repository's page to ensure that the project files have been published successfully.

### Task Submission

Take a screenshot of your modified React application running in the browser.

Share the screenshot in the comment section of the issue

Provide the GitHub repository URL as your submission.

**Comment by junuthapa011** [comment]
Name: Junu Thapa
Github URL: https://github.com/junuthapa011/myreatapp-task3.git

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133033600/2e1055f1-cf9e-43e4-ba57-eb40a5355b8b)

**Comment by Namsla** [comment]
Namkhang Tsamchoe
Github link:https://github.com/Namsla/React-project.git
react link: http://localhost:5173/


<img width="1142" alt="Screen Shot 2023-05-17 at 11 07 32 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/03b793b6-bed7-4283-be6f-126cd3b27682">
localhost:5173

<img width="937" alt="Screen Shot 2023-05-17 at 10 56 46 PM" src="https://github.com/yogeshtakeo/bootcamp_FD30/assets/129420376/abf731ba-db32-4565-a35b-3387cd0a4100">

**Comment by ashmaupret100** [comment]
Name: Ashma Upreti
Github Url: https://github.com/ashmaupret100/react_learn_third.git



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/4c2680bb-1133-4075-afd1-0520e1bc6389)



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/15636a80-ddbc-4ddf-af70-be97ac27c78f)

**Comment by dinakc** [comment]
Deena KC
https://github.com/dinakc/Vite-app.git


![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/105759959/9144caa4-f5f9-4cf4-b05c-c2eb94e7e8e7)



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/105759959/ab03885f-1f3b-426c-a615-0a8463d1fb34)

**Comment by KabinaThapa** [comment]
Kabina Thapa
https://github.com/KabinaThapa/my-react-app-task2/tree/master



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/2559e6a0-532e-4266-963d-4ea1b775da31)
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/b3cca9ff-60b0-4033-b553-5ab0ee15be7e)
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/108284958/f4141f85-c99e-4ea8-a771-19f0c3f8c16b)

**Comment by sandessth** [comment]
Name: Sandesh Shrestha
Github repository: https://github.com/sandessth/my-react-app


![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729653/a726ee62-3436-4719-a0a7-18387bffc64d)
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729653/b8056d45-2e3e-4d40-8593-40831ca3ea60)

**Comment by ashmaupret100** [comment]
Name : Ashma Upreti
Github url: https://github.com/ashmaupret100/react_learn_third.git

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/79654872/d4ee8cd7-688f-4e8e-b5a4-2cf2c0eec476)

**Comment by Jharanatmg** [comment]
Jharana
web url-http://localhost:5173/
GitHub url- https://github.com/Jharanatmg/my-react-app.git

![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729796/ab58342c-a9d6-4b40-b436-19250ac5f191)



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/133729796/6659f9ea-c518-4ccf-9d98-398ae63a079f)

**Comment by babisha** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/23157110/208024fe-9592-4f79-a6b2-dc7e29a51d96)
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/23157110/6739866e-2278-4e0e-bc6c-f2649ead5eca)

**Comment by yogeshtakeo** [comment]
@junuthapa011 @Jharanatmg @Namsla  While the output is correct, a little creativity is needed adding more things and apply yourself in this feild.

**Comment by yogeshtakeo** [comment]
//

**Comment by yogeshtakeo** [comment]
@ashmaupret100 A bit more content with the use of paddings and borders could be updated. Try to go all out on the precious session we have.

Update:
I see you have two submissions on the issue comments can you try on making just one submission next time

**Comment by yogeshtakeo** [comment]
@dinakc I can see the implementation is correct the design is satisfactory. Try to add a bit more UI concepts while designing.

**Comment by yogeshtakeo** [comment]
@sdhital12 Remaining to submit

**Comment by sdhital12** [comment]
![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/110055420/aa2409d9-c868-4aa7-9eaa-7367b422a096)



![Image](https://github.com/yogeshtakeo/bootcamp_FD30/assets/110055420/7c0e9a24-1074-4161-a4ad-8eb72f756c40)
